name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write
jobs:
  release:
    strategy:
      matrix:
        os: [macos-arm64]
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18"
      - name: Release ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          make release-linux-x86_64
      - name: Release darwin x86_64
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          make release-darwin-x86_64
      - name: Release darwin arm64
        if: ${{ matrix.os == 'macos-arm64' }}
        run: |
          make release-darwin-aarch64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/all/*